const cards = {
  triangleGreen1: {
    color: "green",
    shape: "triangle",
    number: 1,
    trialNumber: 1,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/triangle_green_1.png",
    colorRule: 1,
    shapeRule: 0,
    numberRule: 0,
  },
  diamondRed4: {
    color: "red",
    shape: "diamond",
    number: 4,
    trialNumber: 2,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/diamond_red_4.png",
    colorRule: 0,
    shapeRule: 2,
    numberRule: 3,
  },
  triangleBlue2: {
    color: "blue",
    shape: "triangle",
    number: 2,
    trialNumber: 3,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/triangle_blue_2.png",
    colorRule: 3,
    shapeRule: 0,
    numberRule: 1,
  },
  circleRed1: {
    color: "red",
    shape: "circle",
    number: 1,
    trialNumber: 4,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/circle_red_1.png",
    colorRule: 0,
    shapeRule: 3,
    numberRule: 0,
  },
  starGreen4: {
    color: "green",
    shape: "star",
    number: 4,
    trialNumber: 5,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/star_green_4.png",
    colorRule: 1,
    shapeRule: 1,
    numberRule: 3,
  },
  diamondYellow1: {
    color: "yellow",
    shape: "diamond",
    number: 1,
    trialNumber: 6,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/diamond_yellow_1.png",
    colorRule: 2,
    shapeRule: 2,
    numberRule: 0,
  },
  triangleBlue4: {
    color: "blue",
    shape: "triangle",
    number: 4,
    trialNumber: 7,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/triangle_blue_4.png",
    colorRule: 3,
    shapeRule: 0,
    numberRule: 3,
  },
  circleRed3: {
    color: "red",
    shape: "circle",
    number: 3,
    trialNumber: 8,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/circle_red_3.png",
    colorRule: 0,
    shapeRule: 3,
    numberRule: 2,
  },
  diamondGreen4: {
    color: "green",
    shape: "diamond",
    number: 4,
    trialNumber: 9,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/diamond_green_4.png",
    colorRule: 1,
    shapeRule: 2,
    numberRule: 3,
  },
  circleYellow2: {
    color: "yellow",
    shape: "circle",
    number: 2,
    trialNumber: 10,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/circle_yellow_2.png",
    colorRule: 2,
    shapeRule: 3,
    numberRule: 1,
  },
  starBlue1: {
    color: "blue",
    shape: "star",
    number: 1,
    trialNumber: 11,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/star_blue_1.png",
    colorRule: 3,
    shapeRule: 1,
    numberRule: 0,
  },
  triangleRed3: {
    color: "red",
    shape: "triangle",
    number: 3,
    trialNumber: 12,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/triangle_red_3.png",
    colorRule: 0,
    shapeRule: 0,
    numberRule: 2,
  },
  diamondBlue2: {
    color: "blue",
    shape: "diamond",
    number: 2,
    trialNumber: 13,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/diamond_blue_2.png",
    colorRule: 3,
    shapeRule: 2,
    numberRule: 1,
  },
  starYellow1: {
    color: "yellow",
    shape: "star",
    number: 1,
    trialNumber: 14,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/star_yellow_1.png",
    colorRule: 2,
    shapeRule: 1,
    numberRule: 0,
  },
  triangleGreen3: {
    color: "green",
    shape: "triangle",
    number: 3,
    trialNumber: 15,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/triangle_green_3.png",
    colorRule: 1,
    shapeRule: 0,
    numberRule: 2,
  },
  circleBlue4: {
    color: "blue",
    shape: "circle",
    number: 4,
    trialNumber: 16,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/circle_blue_4.png",
    colorRule: 3,
    shapeRule: 3,
    numberRule: 3,
  },
  starRed2: {
    color: "red",
    shape: "star",
    number: 2,
    trialNumber: 17,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/star_red_2.png",
    colorRule: 0,
    shapeRule: 1,
    numberRule: 1,
  },
  circleYellow3: {
    color: "yellow",
    shape: "circle",
    number: 3,
    trialNumber: 18,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/circle_yellow_3.png",
    colorRule: 2,
    shapeRule: 3,
    numberRule: 2,
  },
  triangleRed4: {
    color: "red",
    shape: "triangle",
    number: 4,
    trialNumber: 19,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/triangle_red_4.png",
    colorRule: 0,
    shapeRule: 0,
    numberRule: 3,
  },
  circleYellow1: {
    color: "yellow",
    shape: "circle",
    number: 1,
    trialNumber: 20,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/circle_yellow_1.png",
    colorRule: 2,
    shapeRule: 3,
    numberRule: 0,
  },
  starBlue2: {
    color: "blue",
    shape: "star",
    number: 2,
    trialNumber: 21,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/star_blue_2.png",
    colorRule: 3,
    shapeRule: 1,
    numberRule: 1,
  },
  diamondGreen3: {
    color: "green",
    shape: "diamond",
    number: 4,
    trialNumber: 22,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/diamond_green_4.png",
    colorRule: 1,
    shapeRule: 2,
    numberRule: 3,
  },
  starYellow2: {
    color: "yellow",
    shape: "green",
    number: 2,
    trialNumber: 23,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/star_yellow_2.png",
    colorRule: 2,
    shapeRule: 1,
    numberRule: 1,
  },
  triangleBlue3: {
    color: "blue",
    shape: "triangle",
    number: 3,
    trialNumber: 24,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/triangle_blue_3.png",
    colorRule: 3,
    shapeRule: 0,
    numberRule: 2,
  },
  starRed4: {
    color: "red",
    shape: "star",
    number: 4,
    trialNumber: 25,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/star_red_4.png",
    colorRule: 0,
    shapeRule: 1,
    numberRule: 3,
  },
  triangleYellow2: {
    color: "yellow",
    shape: "triangle",
    number: 2,
    trialNumber: 26,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/triangle_yellow_2.png",
    colorRule: 2,
    shapeRule: 0,
    numberRule: 1,
  },
  diamondBlue3: {
    color: "blue",
    shape: "diamond",
    number: 3,
    trialNumber: 27,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/diamond_blue_3.png",
    colorRule: 3,
    shapeRule: 2,
    numberRule: 2,
  },
  circleRed4: {
    color: "red",
    shape: "circle",
    number: 4,
    trialNumber: 28,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/circle_red_4.png",
    colorRule: 0,
    shapeRule: 3,
    numberRule: 3,
  },
  starGreen2: {
    color: "green",
    shape: "star",
    number: 2,
    trialNumber: 29,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/star_green_2.png",
    colorRule: 1,
    shapeRule: 1,
    numberRule: 1,
  },
  diamondRed1: {
    color: "red",
    shape: "diamond",
    number: 1,
    trialNumber: 30,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/diamond_red_1.png",
    colorRule: 0,
    shapeRule: 2,
    numberRule: 0,
  },
  circleGreen4: {
    color: "green",
    shape: "circle",
    number: 4,
    trialNumber: 31,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/circle_green_4.png",
    colorRule: 1,
    shapeRule: 3,
    numberRule: 3,
  },
  starRed1: {
    color: "red",
    shape: "star",
    number: 1,
    trialNumber: 32,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/star_red_1.png",
    colorRule: 0,
    shapeRule: 1,
    numberRule: 0,
  },
  circleBlue3: {
    color: "blue",
    shape: "circle",
    number: 3,
    trialNumber: 33,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/circle_blue_3.png",
    colorRule: 3,
    shapeRule: 3,
    numberRule: 2,
  },
  diamondYellow4: {
    color: "yellow",
    shape: "diamond",
    number: 4,
    trialNumber: 34,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/diamond_yellow_4.png",
    colorRule: 2,
    shapeRule: 2,
    numberRule: 3,
  },
  starGreen1: {
    color: "green",
    shape: "star",
    number: 1,
    trialNumber: 35,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/star_green_1.png",
    colorRule: 1,
    shapeRule: 1,
    numberRule: 0,
  },
  triangleYellow4: {
    color: "yellow",
    shape: "triangle",
    number: 4,
    trialNumber: 36,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/triangle_yellow_4.png",
    colorRule: 2,
    shapeRule: 0,
    numberRule: 3,
  },
  circleBlue2: {
    color: "blue",
    shape: "circle",
    number: 2,
    trialNumber: 37,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/circle_blue_2.png",
    colorRule: 3,
    shapeRule: 3,
    numberRule: 1,
  },
  starYellow3: {
    color: "yellow",
    shape: "star",
    number: 3,
    trialNumber: 38,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/star_yellow_3.png",
    colorRule: 2,
    shapeRule: 1,
    numberRule: 2,
  },
  circleGreen1: {
    color: "green",
    shape: "circle",
    number: 1,
    trialNumber: 39,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/circle_green_1.png",
    colorRule: 1,
    shapeRule: 3,
    numberRule: 0,
  },
  diamondBlue4: {
    color: "blue",
    shape: "diamond",
    number: 4,
    trialNumber: 40,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/diamond_blue_4.png",
    colorRule: 3,
    shapeRule: 2,
    numberRule: 3,
  },
  triangleRed1: {
    color: "red",
    shape: "triangle",
    number: 1,
    trialNumber: 41,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/triangle_red_1.png",
    colorRule: 0,
    shapeRule: 0,
    numberRule: 0,
  },
  starBlue3: {
    color: "blue",
    shape: "star",
    number: 3,
    trialNumber: 42,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/star_blue_3.png",
    colorRule: 3,
    shapeRule: 1,
    numberRule: 2,
  },
  circleYellow4: {
    color: "yellow",
    shape: "circle",
    number: 4,
    trialNumber: 43,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/circle_yellow_4.png",
    colorRule: 2,
    shapeRule: 3,
    numberRule: 3,
  },
  triangleGreen2: {
    color: "green",
    shape: "triangle",
    number: 2,
    trialNumber: 44,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/triangle_green_2.png",
    colorRule: 1,
    shapeRule: 0,
    numberRule: 1,
  },
  starRed3: {
    color: "red",
    shape: "star",
    number: 3,
    trialNumber: 45,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/star_red_3.png",
    colorRule: 0,
    shapeRule: 1,
    numberRule: 2,
  },
  diamondYellow2: {
    color: "yellow",
    shape: "diamond",
    number: 2,
    trialNumber: 46,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/diamond_yellow_2.png",
    colorRule: 2,
    shapeRule: 2,
    numberRule: 1,
  },
  circleBlue1: {
    color: "blue",
    shape: "circle",
    number: 1,
    trialNumber: 47,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/circle_blue_1.png",
    colorRule: 3,
    shapeRule: 3,
    numberRule: 0,
  },
  triangleYellow3: {
    color: "yellow",
    shape: "triangle",
    number: 3,
    trialNumber: 48,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/triangle_yellow_3.png",
    colorRule: 2,
    shapeRule: 0,
    numberRule: 2,
  },
  diamondGreen2: {
    color: "green",
    shape: "diamond",
    number: 2,
    trialNumber: 49,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/diamond_green_2.png",
    colorRule: 1,
    shapeRule: 2,
    numberRule: 1,
  },
  starYellow4: {
    color: "yellow",
    shape: "star",
    number: 4,
    trialNumber: 50,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/star_yellow_4.png",
    colorRule: 2,
    shapeRule: 1,
    numberRule: 3,
  },
  triangleBlue1: {
    color: "blue",
    shape: "triangle",
    number: 1,
    trialNumber: 51,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/triangle_blue_1.png",
    colorRule: 3,
    shapeRule: 0,
    numberRule: 0,
  },
  starGreen3: {
    color: "green",
    shape: "star",
    number: 3,
    trialNumber: 52,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/star_green_3.png",
    colorRule: 1,
    shapeRule: 1,
    numberRule: 2,
  },
  circleRed2: {
    color: "red",
    shape: "circle",
    number: 2,
    trialNumber: 53,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/circle_red_2.png",
    colorRule: 0,
    shapeRule: 3,
    numberRule: 1,
  },
  triangleGreen4: {
    color: "green",
    shape: "triangle",
    number: 4,
    trialNumber: 54,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/triangle_green_4.png",
    colorRule: 1,
    shapeRule: 0,
    numberRule: 3,
  },
  diamondBlue1: {
    color: "blue",
    shape: "diamond",
    number: 1,
    trialNumber: 55,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/diamond_blue_1.png",
    colorRule: 3,
    shapeRule: 2,
    numberRule: 0,
  },
  circleGreen3: {
    color: "green",
    shape: "circle",
    number: 3,
    trialNumber: 56,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/circle_green_3.png",
    colorRule: 1,
    shapeRule: 3,
    numberRule: 2,
  },
  diamondRed2: {
    color: "red",
    shape: "diamond",
    number: 2,
    trialNumber: 57,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/diamond_red_2.png",
    colorRule: 0,
    shapeRule: 2,
    numberRule: 1,
  },
  triangleYellow1: {
    color: "yellow",
    shape: "triangle",
    number: 1,
    trialNumber: 58,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/triangle_yellow_1.png",
    colorRule: 2,
    shapeRule: 0,
    numberRule: 0,
  },
  diamondRed3: {
    color: "red",
    shape: "diamond",
    number: 3,
    trialNumber: 59,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/diamond_red_3.png",
    colorRule: 0,
    shapeRule: 2,
    numberRule: 2,
  },
  circleGreen2: {
    color: "green",
    shape: "circle",
    number: 2,
    trialNumber: 60,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/circle_green_2.png",
    colorRule: 1,
    shapeRule: 3,
    numberRule: 1,
  },
  starBlue4: {
    color: "blue",
    shape: "star",
    number: 4,
    trialNumber: 61,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/star_blue_4.png",
    colorRule: 3,
    shapeRule: 1,
    numberRule: 3,
  },
  diamondYellow3: {
    color: "yellow",
    shape: "diamond",
    number: 3,
    trialNumber: 62,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/diamond_yellow_3.png",
    colorRule: 2,
    shapeRule: 2,
    numberRule: 2,
  },
  triangleRed2: {
    color: "red",
    shape: "triangle",
    number: 2,
    trialNumber: 63,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/triangle_red_2.png",
    colorRule: 0,
    shapeRule: 0,
    numberRule: 1,
  },
  diamondGreen1: {
    color: "green",
    shape: "diamond",
    number: 1,
    trialNumber: 64,
    image:
      "https://cdn.jsdelivr.net/gh/vekteo/Card_sorting_jsPsych/static/images/diamond_green_1.png",
    colorRule: 1,
    shapeRule: 2,
    numberRule: 0,
  },
};
